services:
  web:
    build:
      context: ..
      dockerfile: docker-config/Dockerfile
    container_name: vesti-dev
    ports:
      - "3000:3000"

    env_file:
      - ../apps/web/.env.local
    stdin_open: true
    tty: true